### ISSUE TITLE
[v2] docz css pollute the `<Playground>`

### ISSUE THREAD

**Issue by crusoexia** [doczjs/docz#1170]
## Bug Report

**Describe the bug**

Seems like there is no css isolation between the doc style and the live playground, user's component will be polluted by docz's css.

```mdx
<Playground name="Default">
  <Accordion>
    <AccordionPanel active title="Lil Mud Runner kids1">
       Some text
    </AccordionPanel>
  </Accordion>
</Playground>
```

**Expected behavior**

docz's css should not pollute the playground

**Environment**

- docz version: ^2.0.0-rc.55
- OS: MacOS 10.14.6
- Node/npm version: 10.15.0/6.12.0

** screenshot **

polluted:

![Screen Shot 2019-10-12 at 9 57 56 AM](https://user-images.githubusercontent.com/5928754/66693022-db6cae00-ecd6-11e9-8e3c-d4fc479819e8.png)

What it should like:

![Screen Shot 2019-10-12 at 9 58 09 AM](https://user-images.githubusercontent.com/5928754/66693032-f5a68c00-ecd6-11e9-825f-9c80f0420dfb.png)

**Comment by rakannimer** [comment]
@stale Not stale.

Hey @crusoexia 

This is solved in 2.2.0. 

To scope your playground styles and make them independent of docz theme css you have 2 choices : 

1. add a useScoping prop to your playground

```jsx
<Playground useScoping> 
{
// blablabla
}
</Playground>
```
2. add `useScopingInPlayground : true` in doczrc.js 

```js
export default {
	useScopingInPlayground: true
}
```

Sorry for the delay in the reply but the fix was implemented thanks to you raising this issue ! So thanks 👍 

Going to close, please re-open or comment if for some reason something doesn't work for you !
