### ISSUE TITLE
Code shadowing

### ISSUE THREAD

**Issue by sorknes** [doczjs/docz#1433]
## Code shadowing don't work as described?

**Description**
I'm trying to change the Header/index.js file. This is my folder structure:
`root/src/gatsby-theme-docz/src/components/Header/index.js`. I don't get any errors and nothing happens.

I added a new `root/src/gatsby-theme-docz/wrapper.js`file, and that works...

What am I doing wrong?

I tried using both `yarn create docz-app my-docz-app` and `yarn create docz-app docz-app-gatsby --example gatsby`

**Comment by sorknes** [comment]
It's important to use the right path. This is correct: `root/src/gatsby-theme-docz/components/Header/index.js`

Also remember to add other file dependecies.

**Comment by oliikit** [comment]
That seems a bit counter intuitive to what shadowing _should_ do. You should be able to extend it (see [Gatsby docs](https://www.gatsbyjs.org/docs/themes/shadowing/#extending-shadowed-files))

**Comment by drewlustro** [comment]
@sorknes - What if my `root` and `src` directories are the same? What file path should I use to replace `wrapper.js` of **gatsby-theme-docz** ?

```js
// docz.js

export default {
  root: __dirname,
  src: __dirname,
  // ...

}
```


My components exist in `projectRoot/components`, but I also want to pick up `.mdx` files in other subdirectories, so that's why root and src are the same.

At the moment, I'm trying `projectRoot/gatsby-theme-docz/wrapper.js` but it does not work.

```jsx
import React from 'react';

// @ts-ignore
import styles from './styles.scss';

const Wrapper = ({ children }) => {
  console.log('Shadowed <Wrapper>!');

  return (
    <div className={styles.component} style={{ backgroundColor: 'red'}}>
      {children}
    </div>
  );
}

export default Wrapper;
```

That `console.log` never gets evaluated.
