### ISSUE TITLE
Error: Cannot find module 'dotenv'

### ISSUE THREAD

**Issue by sw-yx** [doczjs/docz#1444]
## Bug Report

**Describe the bug**

Out of the box installation has `Error: Cannot find module 'dotenv'` error.

**To Reproduce**

Following basic instructions on the landing page:

1. `yarn add docz react react-dom --dev`
2. Create an .mdx file
3. yarn docz dev

**Expected behavior**

It should just work.

**Environment**

- docz version: 2.3.0
- OS: osx 10.15.4
- Node/npm version: Node 12.16.1

![image](https://user-images.githubusercontent.com/6764957/78419379-bc444d00-7677-11ea-8557-cde6fb4aab08.png)

**Comment by rakannimer** [comment]
Hey @sw-yx,

Thanks for reporting this, and I'm sorry this is happening with you.

Could you please share the other dependencies you're using or a link to a repro ? 

I tried to reproduce but couldn't so I'm guessing this is due to a conflict or something unexpected happening with other dependencies.

**Comment by sw-yx** [comment]
hey! yeah dont worry about it i was running with an extremely custom setup with preact instead of react. that probably caused it. I'll close it now but if anyone comes across this in future they can check out my repo https://github.com/sw-yx/smaller-safer-serverless-starter/ (rakannimer pls dont waste time on this)
