### ISSUE TITLE
Can I modify `propFilter`?

### ISSUE THREAD

**Issue by donifer** [doczjs/docz#337]
## Question
Hi, is there a way I can modify docgen-typescript's `propsFilter`?

**Description**
I have the same exact issue as https://github.com/styleguidist/react-docgen-typescript/pull/111 were my PropsTable is populated with *all* the html props/attrs which makes it a bit hard to use. I was wondering if there is a way I can pass the same function as he is using:

```
propFilter: (prop) => {
      if (prop.parent == null) {
        return true;
      }

      return prop.parent.fileName.indexOf('node_modules/@types/react') < 0;
    }
```

Seems like thats all I should need

**Comment by pedronauck** [comment]
Unfortunately, right now we're very restricted about the react-docgen configuration because the `babel-plugin-react-docgen` and the loader, but we're working to improve this 🙏

**Comment by bntzio** [comment]
Any updates on this?

**Comment by rkusa** [comment]
It looks like we can provide a `propFilter` inside our `doczrc.js` config (https://github.com/pedronauck/docz/blob/c0749d32d9b806b8a83fb91f0dbb34203585df4f/core/docz-core/src/config/argv.ts#L97). E.g.

```js
docgenConfig: {
    propFilter: (prop) => {
      if (!prop.parent) {
        return true;
      }

      return prop.parent.fileName.indexOf('node_modules/@types/react') < 0;
    }
  }
```

However, it looks like `prop.parent` is always `undefined`, even for properties coming from `extends React.HTMLAttributes<HTMLButtonElement>`. So this approach doesn't seem to work for `docz`.

**Comment by rkusa** [comment]
For everyone coming to this issue, I think I finally found out what is going on here. For the use case of this issue, we don't really need the custom `propFilter`, since docz already ignores properties coming from `node_module`s. However, they were still not filtered out for me.

The issue was, that docz' `propFilter` still always received a `prop` with `parent` being `undefined`. `react-docgen-typescript` will only set the `prop.parent` (see snippet of previous comment), if the encountered parent kind is either `InterfaceDeclaration ` or `TypeAliasDeclaration`. As you can see [here](https://github.com/microsoft/TypeScript/blob/master/lib/typescript.d.ts#L325-L326), those are mapped by numbers. Now, those numbers seem to change between typescript versions and while my app was using typescript `3.7`, `docz-core` uses `3.5`, this lead to a configuration where my parent interfaces (e.g. `React.HTMLAttributes`) had the kind `242`, which was then mapped to `VariableDeclarationList`, which is obviously neither  `InterfaceDeclaration` nor `TypeAliasDeclaration`.

I was able to fix this issue for me by forcing one `typescript` version via (inside my `package.json`):

```json
  "resolutions": {
    "typescript": "3.7.3"
  },
```

**Comment by drewlustro** [comment]
@rkusa – Thank you for the hint!

Where in the code does it enforce a filter on `InterfaceDeclaration` or `TypeAliasDeclaration` to set `parent` appropriately?

I'm trying to understand where the brittle code is so that I may patch. I don't want to be stuck on an old version of TypeScript just to get the correct numeric AST identifiers.

**Comment by rkusa** [comment]
@drewlustro Quite a while ago so I am not entirely sure anymore, but from a quick glance it looks like to [be this cod](https://github.com/styleguidist/react-docgen-typescript/blob/d56828871721c0e8711dae71b6b17d76a568bb78/src/parser.ts#L1348-L1349)e (`parent` not set [here](https://github.com/styleguidist/react-docgen-typescript/blob/d56828871721c0e8711dae71b6b17d76a568bb78/src/parser.ts#L1331-L1333), because this function returns false).

**Comment by drewlustro** [comment]
Lovely, I just figured it out! 

For those that come through in the future, these resolutions worked:

```js
// package.json

"resolutions": {
  "**/react-docgen-typescript": "2.2.2",
  "typescript": "4.4.3",
  "**/typescript": "4.4.3"
}
```

**Comment by drewlustro** [comment]
To build upon @rkusa's code reference:

It doesn't appear to matter which TypeScript version you're on. What matters is that the version is **consistent** such that the following condition refers to the same constants:

```tsx
function isInterfaceOrTypeAliasDeclaration(
  node: ts.Node
): node is ts.InterfaceDeclaration | ts.TypeAliasDeclaration {
  return (
    node.kind === ts.SyntaxKind.InterfaceDeclaration ||
    node.kind === ts.SyntaxKind.TypeAliasDeclaration
  );
}
```
> buried in `react-docgen-typescript`
