### ISSUE TITLE
tslint mdx files

### ISSUE THREAD

**Issue by mattietea** [doczjs/docz#796]
## Question
Anyone have success using tslint with docz? 

**Description**

I've seen this [issue](https://github.com/pedronauck/docz/issues/340#issuecomment-425154908) but does anyone have a complete example?

Thanks a lot!

*Give more information about your doubt*

* Twitter: If it's just a quick question you can ping me on Twitter: https://twitter.com/pedronauck

**Comment by JoshRosenstein** [comment]
The OP of that issue sounds like he wanted his editor to flag the type errors which is currently a limitation of mdx file. See [mdx/Intellisense / Typescript](https://github.com/mdx-js/mdx/issues/510)
Also since tslint is slowly going [away](https://github.com/palantir/tslint/issues/4534) should look for eslint solutions. Somthing like [eslint-plugin-mdx](https://github.com/azz/eslint-plugin-mdx).

I havent used any custom plugins of config options yets for docz so i cant help ya on the modifyBundlerConfig example.

But a quick github search I found [this](https://github.com/ifiokjr/remirror/blob/bebb1810cdb007ccead6dd8bf0f44489b2f264f8/doczrc.js), I would believe to a good base to go off of.
