### ISSUE TITLE
`ref` and `key` are not omitted from Props-generated table

### ISSUE THREAD

**Issue by disintegrator** [doczjs/docz#921]
## Bug Report

**Describe the bug**

`Props` component includes `ref` and `key` props in props table when passed a component created with `React.forwardRef`. I would argue these props should not be exposed because they cannot be documented in our code. They are also part of React's API in that they are documented elsewhere and considered assumed knowledge in our docs.

**To Reproduce**

Create this component

```tsx
// docs/Faulty.tsx

import React from "react";

export interface FaultyProps {}

const Faulty = React.forwardRef<HTMLDivElement>((props, ref) => {
  return <div ref={ref}>{props.children}</div>;
});

export default Faulty;
```

With this documentation

```
{/* docs/Faulty.mdx */}

import { Props } from "docz";
import Faulty from "./Faulty";

# Faulty

<Props of={Faulty} />
```

**Expected behavior**

`ref` and `key` are omitted from generated props table

**Environment**

* OS: macOS 10.14.5
* Node version: 10.15.3
* Yarn version: 1.16.0
* Docz packages:
```json
{
  "docz": "1.2.0",
  "docz-theme-default": "1.2.0"
}
```

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/678548/59597856-b71b0f00-90f2-11e9-805a-2282d076a6a1.png)

**Comment by disintegrator** [comment]
For what it's worth, I tried passing custom `docgenConfig` but since it `propFilter` must be a function, it is not parsed correctly by `load-cfg`.

**Comment by ejuo** [comment]
I encountered a similar problem. Moreover, earlier on the same version of docz it was OK, perhaps this is due to the update of third libraries.
The problem is that when calling [props.parent](https://github.com/pedronauck/docz/blob/master/core/docz-core/src/utils/docgen/typescript.ts#L162) (https://github.com/styleguidist/react-docgen-typescript/issues/151), it is always null. And therefore all properties fall into the props table. 
It is also interesting that if I builld examples from the docz repository, then the props.paren check works.
