### ISSUE TITLE
Props component doesn`t render props table with typescript

### ISSUE THREAD

**Issue by Viktor19931** [doczjs/docz#935]
## Bug Report
**docz config**

> export default {
>  title: 'Documentation',
>  typescript: true,
>  codeSandbox: false,
>  description: 'Documentation from the Components',
> };

**my component**
```
import React, { SFC } from 'react'
import styled from 'styled-components'

const scales = {
  small: `
    padding: 5px 10px;
    font-size: 14px;
  `,
  normal: `
    padding: 10px 20px;
    font-size: 16px;
  `,
  big: `
    padding: 20px 30px;
    font-size: 18px;
  `,
}

const kind = (outline: boolean) => (bg: string, color: string) => {
  const boxShadowColor = outline ? bg : 'transparent'
  const backgroundColor = outline ? 'transparent' : bg

  return `
    background: ${backgroundColor};
    box-shadow: inset 0 0 0 1px ${boxShadowColor};
    color: ${outline ? bg : color};
    transition: all .3s;

    &:hover {
      box-shadow: inset 0 0 0 1000px ${boxShadowColor};
      color: ${color};
    }
  `
}

type Kind = 'primary' | 'secondary' | 'cancel' | 'dark' | 'gray'
type Kinds = Record<Kind, string>

const kinds = (outline: boolean): Kinds => {
  const get = kind(outline)

  return {
    primary: get('#1FB6FF', 'white'),
    secondary: get('#5352ED', 'white'),
    cancel: get('#FF4949', 'white'),
    dark: get('#273444', 'white'),
    gray: get('#8492A6', 'white'),
  }
}

export interface ButtonProps {
  scale: 'small' | 'normal' | 'big'
  kind: 'primary' | 'secondary' | 'cancel' | 'dark' | 'gray'
  outline: boolean
}

const getScale = ({ scale = 'normal' }: ButtonProps) => scales[scale]
const getKind = ({ kind = 'primary', outline = false }: ButtonProps) =>
  kinds(outline)[kind]

const ButtonStyled = styled('button')`
  ${getKind};
  ${getScale};
  cursor: pointer;
  margin: 3px 5px;
  border: none;
  border-radius: 3px;
`

export const Button: SFC<ButtonProps> = ({ children, ...props }) => (
  <ButtonStyled {...props}>{children}</ButtonStyled>
)
```

**use in mdx file**

```
import { Playground, Props } from 'docz';
<Props of={Button} />
```

but unfortunately it is not render table

**Current behavior**
Props Component doesn't render table with props

```
import { Playground, Props } from 'docz';
import { Button } from './index.tsx';
<Props of={Button} />
```

**Expected behavior**
Props component should render table with props 

Also try to run official docz typescript example, but still not render table

**Environment**
* docz 1.2.0
* docz-theme-default 1.2.0
* OS: OSX 10.14.5
* Node/npm version: 10.16.0/6.9.0

**Comment by jleck** [comment]
+1 Also have this issue

**Comment by canyavall** [comment]
+1 We also have this issue
In our case we are working with React-Native, I'm not sure if it is related.

Another thing I've seen is that there's a warning saying:
'React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.'

I don't know if it is related or not.

If we check the <Props></Props> component in the devtools, it is kust empty...

**Comment by Heluwe** [comment]
+1 But sometimes it's works

**Comment by MatanMaimon** [comment]
+1 here, same issue

**Comment by xiangfengsu** [comment]
+1 here, same issue

**Comment by alexluong** [comment]
+1

**Comment by JoseLAmador** [comment]
+1 🤔

**Comment by yonatan-rojas** [comment]
+1

**Comment by RedYaafte** [comment]
+1

**Comment by alanllamas** [comment]
+1

**Comment by coderdiaz** [comment]
How can I contribute to this project? Any `contribution` documentation about?

**Comment by ncordin** [comment]
+1

**Comment by axe312ger** [comment]
Same for non-typescript environment

**Comment by axe312ger** [comment]
Wow, this took some time, but after digging deeper into the source, I found two reasons, why it won't render any props for me. Now I got it rendering 😏 

![Screenshot 2019-08-24 at 01 19 21](https://user-images.githubusercontent.com/1737026/63628544-4e2da700-c60d-11e9-8f84-198f0a23d99f.png)

## Thats broken (for me):

### Everything in `node_modules` get excluded

https://github.com/pedronauck/docz/blob/cfe07b0c00fa5ff73bd194fbc48240a5315bc10e/core/docz-core/src/states/props.ts#L30

This breaks parsing the props since I try to render docs for some dependencies.

For now I can work around since my lerna repo has the files outside of `node_modules` as well. Later on, I need to render props from selected dependencies.

Anybody doing similar? We could have a flag to exclude that filter or only ignore files that not include the source string.

### As soon I set a `src` to my components, it fails to generate entries.

Don't see yet why this is related to the entries. But I found a workaround ⬇️ 

## This is how to fix it, might do a PR soon 🤞 

The props parser can actually accept another config to set the components path. It's called `docgenConfig`. Unfortunately, the default config overwrites the given config. I thing this is a bug.

https://github.com/pedronauck/docz/blob/cfe07b0c00fa5ff73bd194fbc48240a5315bc10e/core/docz-core/src/config/docz.ts#L36

So we could just replace

```js
 const base = { ...initial, ...doczRcBaseConfig, paths }
```
with 

```js
const base = { ...doczRcBaseConfig, ...initial, paths }
```

Since `initial` contains the users config, which should extend the base config and not the other way around.

This way I can simply add the following to my `gatsby-config.js` to get the props parsed and rendered:

```js
{
  resolve: `gatsby-theme-docz`,
  options: {
    docgenConfig: {
      searchPath: path.resolve(
        __dirname,
        '../packages/components'
      ),
    },
  },
},
```

**Comment by gogoyqj** [comment]
well...just add code below to docz.js and it works for me
```
filterComponents: files => files.filter(p => p.match(/ts[x]?$/))
```

**Comment by beeeku** [comment]
> well...just add code below to docz.js and it works for me [#941 (comment)](https://github.com/doczjs/docz/issues/941#issuecomment-518118071)
> 
> ```
> filterComponents: files => files.filter(p => p.match(/ts[x]?$/))
> ```

@gogoyqj can you share your doczrc.js, It will be helpful to others!

**Comment by JoseLAmador** [comment]
@beeeku Works!, change your `doczrc.js` config:

```js
export default {
  filterComponents: (files) =>
    files.filter(filepath => /[w-]*.(js|jsx|ts|tsx)$/.test(filepath)),
}
``` 
**Note:** First remove your .docz and try it! 🍻

**Comment by beeeku** [comment]
### Can't Confirm Why But This **WORKS** !!!

**Comment by PaulieScanlon** [comment]
I had a similar issue, and with`.tsconfig.json` and `doczrc.js` all setup as it should be i found that after some time it was **always** working!... 

I just had to delete `.docz` and run the build again... You might see in terminal that it says cache is missing and prop types will need to be generated, after the build completes the PropTables were populated as expected.

**Comment by jugglingcats** [comment]
@PaulieScanlon do your props update when you change the component definition? I can get the props to refresh if I stop dev server, delete `.docz` and start again, but this is a pain on every prop change!

**Comment by PeteJodo** [comment]
I had a similar issue and it was because the props table it was trying to render was for the component exported from the file `MyComponent.test.tsx` rather than `MyComponent.tsx` which had correctly generated documentation for, the check just happened to test the test file before my actual file and matched. The check where this was happening and matching test files occurs [here](https://github.com/doczjs/docz/blob/master/core/docz/src/hooks/useComponentProps.ts#L21-L29). However the better solution is to have docz ignore test files instead
