### ISSUE TITLE
Point to a specific subdirectory for theme overrides? (2.0)

### ISSUE THREAD

**Issue by Reklino** [doczjs/docz#997]
## Question

**Description**
I'm looking for a way to point to a specific subdirectory for the gatsby theme overrides in 2.0

Currently, I have:
```
+-- doczrc.js
+-- .docz
+-- src
|   +-- gatsby-theme-docz
```

What'd I'm aiming for:
```
+-- doczrc.js
+-- .docz
+-- theme
|   +-- gatsby-theme-docz
```

I haven't come across a straight-forward way to accomplish this in the config. Has anyone had any luck?

**Comment by Dangoo** [comment]
@pedronauck @rakannimer 
What do you think of a theme option named e.g. `overwritePath` (analogous to [gatsby-theme-blog](https://www.gatsbyjs.org/packages/gatsby-theme-blog/#theme-options)) and are you open for a PR?

**Comment by rakannimer** [comment]
Hey ! 

This sounds like a good idea, I'd be happy to merge PRs if you'd like to take this on.

**Comment by Dangoo** [comment]
Hey @rakannimer, 
sure, I might have a look into this.

Can you give me a quick hint on how the overwrite of theme components with custom components works?
As far as I figured, the plugins custom options are passed to a function in [`gatsby-config.js`](https://github.com/doczjs/docz/blob/2f29e1d4a18854bd32618960c97a697df13a85d7/core/gatsby-theme-docz/gatsby-config.js#L31)  and than get extracted here: https://github.com/doczjs/docz/blob/2f29e1d4a18854bd32618960c97a697df13a85d7/core/gatsby-theme-docz/gatsby-config.js#L32

But where exactly is the substitution handled and where would I have to pass the path through?

**Comment by rakannimer** [comment]
Hey @dangoo,

The overwrite happens on Gatsby's side (component shadowing) and is not part of the docz codebase. 

I think Gatsby themes would have to support pointing to a different directory when overriding before we are able to, but I'd be happy to be proven wrong.

Sorry if that's not very helpful!

**Comment by Dangoo** [comment]
Thanks for the hint anyways. Seems I have to dig a bit into Gatsbys theme resolution.
But hey, they even have that covered in an in-depth article, seems like a pretty good place to start!

In case somebody's is interested or faster in reading than me, here's the link:
https://www.gatsbyjs.org/docs/how-shadowing-works/

**Comment by rakannimer** [comment]
Upon further inspection it turns out I was wrong, it should be feasible to assign a custom path for overrides.  

Check these out : 

 - https://github.com/doczjs/docz/blob/d2aff82fb941ca4bcb1d2b01649655c84c94c5c8/core/docz-core/src/bundler/machine/actions.ts#L21 

- https://github.com/doczjs/docz/blob/d2aff82fb941ca4bcb1d2b01649655c84c94c5c8/core/docz-core/src/bundler/machine/services/watch-files.ts#L11


We would need to : 
1. Have the path default `src/gatsby-theme-**` in the docz config
2. Add argument to ensureFiles with the path blob. 
3. Update the watch function [here](https://github.com/doczjs/docz/blob/master/core/docz-core/src/bundler/machine/actions.ts#L21) to use path from config

**Comment by Dangoo** [comment]
@rakannimer for a first draft I chose `themeDir` as option name and it is located on the root level of   `doczrc.js` next to `themeConfig`. It did not seem appropriate within `themeConfig`, since it seems like that config only relates to `gatsby-theme-docz`, while the override path applies for all kinds of (custom) themes.
Any feedback/thoughts about that?

**Comment by rakannimer** [comment]
Very nice PR, that was fast 😄 ! 

Your reasoning makes sense to me, it's better to add themeDir as a separate variable at the top level of the config.

**Comment by Dangoo** [comment]
Thanks @rakannimer for your support and the quick replies! My team really needed that feature and haven’t had such a pleasant contribution experience in while :)

I think we‘re done here. Will you take care on the documentation?

**Comment by rakannimer** [comment]
Yep the docs are in a different repo, I'll make sure to add this flag before the official v2 release. 

Thanks again for your contribution :)
