### ISSUE TITLE
Immediate & overwhelming issues after starting

### ISSUE THREAD

**Issue by StevenLangbroek** [doczjs/docz#999]
## Bug Report

**Describe the bug**

I followed the instructions on the main website (using `docz@next`). First thing that happens after running:

![image](https://user-images.githubusercontent.com/296796/62703084-a9924f00-b9e8-11e9-98f5-bbbc3da8aed6.png)

Frustrating, but just a warning. Moving on. Docz tries to install dependencies, which leads to it crashing and not moving on on this error:

![image](https://user-images.githubusercontent.com/296796/62703124-c3cc2d00-b9e8-11e9-975f-31ffb543367d.png)

After I manually install, this happens again because of `gatsby-plugin-typescript` missing, and then again for `to-style`, so I install those manually. At this point it actually compiles, but I immediately get an error overlay:

![image](https://user-images.githubusercontent.com/296796/62703543-c24f3480-b9e9-11e9-93d5-23796c352c0e.png)

This is #939. And I'm blocked here. I'm unsure what to do now. To recap, I now have:

- Typescript issue #784 
- Unable to start on `@next` because of this.

**Comment by StevenLangbroek** [comment]
I've offered to help and am donating to the project but this is becoming hard to justify at this rate. Sorry if that's harsh, but I'm running out of options and out of time.

**Comment by marinoguerieri** [comment]
The same thing happened to me too. It was driving me nuts because I kept assuming that I was doing something wrong or that something was wrong with my current setup, but now I realize that it's, in fact, a bug.

**Comment by StevenLangbroek** [comment]
Can we pin gatsby to a specific version that doesn't have this issue perhaps?

**Comment by leahprin** [comment]
Same issue here. Any fixes yet?

**Comment by jesperorb** [comment]
@StevenLangbroek @leahprin 

Hi, if you try to run with the latest `@next` (`v2.0.0-rc.52`), are you still getting the same errors?

**Comment by rakannimer** [comment]
Hey all,

I'm sorry you've had this frustrating experience while trying to use `docz` v2.

We've put in a lot of work since the release of `2.0.0-rc.1` and released 67 (at the time of writing) new release candidates.

I'm fairly sure the issues that happened to you are no longer relevant due to the amount of changes in the codebase (for example `docz` no longer needs to install any dependencies and we've added a bunch of e2e tests to avoid any regression )

I'm going to close this issue due to inactivity, but please feel free to re-open it or open a new one if you face any issues or have any questions !
